version: '3.9'

services:
  app:
    container_name: prod-app
    depends_on:
      - postgres
    build: .
  postgres:
    container_name: prod-postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=12345678
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: